#!/usr/bin/env bash
# Interactive .env / .env.local writer. Run once; secrets stay on your disk,
# nothing echoes to history or screen.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")"/.. && pwd)"
LOCAL_ENV="$ROOT_DIR/.env.local"
INGEST_ENV="$ROOT_DIR/ingestion/.env"

echo "IslaGrid environment setup"
echo "=========================="
echo
echo "This will write two files (both gitignored):"
echo "  $LOCAL_ENV"
echo "  $INGEST_ENV"
echo
echo "Each prompt reads silently (your input is not echoed)."
echo "Press Enter to skip a value (leaves it empty)."
echo

read_secret() {
  local prompt="$1"
  local var
  printf "%s: " "$prompt"
  read -rs var
  echo
  printf '%s' "$var"
}

read_plain() {
  local prompt="$1"
  local var
  printf "%s: " "$prompt"
  read -r var
  printf '%s' "$var"
}

echo "--- Supabase ---"
SUPABASE_URL=$(read_plain "Supabase Project URL (https://xxxxx.supabase.co)")
SUPABASE_ANON_KEY=$(read_secret "Supabase anon (publishable) key")
SUPABASE_SERVICE_ROLE_KEY=$(read_secret "Supabase service_role (secret) key")

echo
echo "--- Cloudflare R2 ---"
R2_ACCOUNT_ID=$(read_plain "R2 Account ID (32-char hex)")
R2_ACCESS_KEY_ID=$(read_plain "R2 Access Key ID")
R2_SECRET_ACCESS_KEY=$(read_secret "R2 Secret Access Key")

echo
echo "--- Upstash Redis ---"
UPSTASH_REDIS_REST_URL=$(read_plain "Upstash REST URL (https://us1-...upstash.io)")
UPSTASH_REDIS_REST_TOKEN=$(read_secret "Upstash REST Token")

echo
echo "--- Optional (press Enter to skip) ---"
NREL_API_KEY=$(read_secret "NREL API Key (for /solar)")
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""

echo
echo "--- Generating cryptographic secrets ---"
if command -v openssl >/dev/null 2>&1; then
  API_KEY_PEPPER=$(openssl rand -hex 32)
  REPORT_IP_SALT=$(openssl rand -hex 32)
  echo "Generated API_KEY_PEPPER + REPORT_IP_SALT with openssl."
else
  echo "openssl not found; generating with /dev/urandom"
  API_KEY_PEPPER=$(head -c 32 /dev/urandom | xxd -p -c 32)
  REPORT_IP_SALT=$(head -c 32 /dev/urandom | xxd -p -c 32)
fi

R2_ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

echo
echo "Writing files…"

cat > "$LOCAL_ENV" <<EOF
# Generated by scripts/setup-env.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Edit by hand to fix typos; re-run setup-env.sh to regenerate from scratch.

# --- Supabase (Next.js side) ---
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY

# --- Upstash Redis ---
UPSTASH_REDIS_REST_URL=$UPSTASH_REDIS_REST_URL
UPSTASH_REDIS_REST_TOKEN=$UPSTASH_REDIS_REST_TOKEN

# --- Security ---
API_KEY_PEPPER=$API_KEY_PEPPER
REPORT_IP_SALT=$REPORT_IP_SALT
TRUST_PROXY=false  # set to true on Vercel / Cloudflare

# --- NREL (PVWatts, /solar feature) ---
NREL_API_KEY=$NREL_API_KEY
NREL_API_HOST=developer.nlr.gov

# --- Geocoder (Nominatim) ---
GEOCODER_UA=islagrid-ai/0.1 (iantdm11@gmail.com)
NWS_USER_AGENT=islagrid-ai/0.1 (iantdm11@gmail.com)

# --- Public site (for /api/reports origin allow-list) ---
NEXT_PUBLIC_SITE_URL=http://localhost:3000
EOF
chmod 600 "$LOCAL_ENV"

cat > "$INGEST_ENV" <<EOF
# Generated by scripts/setup-env.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# --- Supabase (server-side) ---
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY

# --- Cloudflare R2 ---
R2_ACCOUNT_ID=$R2_ACCOUNT_ID
R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID
R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY
R2_BUCKET=islagrid-raw
R2_ENDPOINT=$R2_ENDPOINT

# --- NWS / Nominatim User-Agents ---
NWS_USER_AGENT=islagrid-ai/0.1 (iantdm11@gmail.com)
GEOCODER_UA=islagrid-ai/0.1 (iantdm11@gmail.com)

# --- NREL ---
NREL_API_KEY=$NREL_API_KEY
NREL_API_HOST=developer.nlr.gov

# --- Security ---
REPORT_IP_SALT=$REPORT_IP_SALT
EOF
chmod 600 "$INGEST_ENV"

echo
echo "Wrote $LOCAL_ENV (mode 600)"
echo "Wrote $INGEST_ENV (mode 600)"
echo
echo "Done. Both files are gitignored — they will not be committed."
echo
echo "Quick verification:"
ls -la "$LOCAL_ENV" "$INGEST_ENV" 2>&1 | head -3
